# Header
menu:
  主页: /
  所有文章: /archives
  友情链接: /links
  ToMyLove: /love

# SubNav
subnav:
  github: "https://github.com/nooldey"
  weibo: "http://weibo.com/nooldey"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: More
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous 填写统计特征码如id即可
google_analytics: ''
baidu_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: 
#是否开启分享
share_jia: false
#是否显示广告
google_ad: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: none
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
    设计笔记: https://www.idevs.cn/
    免费资源部落: http://www.freehao123.com/
    氪星人: http://defcon.cn/
    ZWW: http://uiv5.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 爱懒觉、纯吃货，从事过硬件维修，超热衷网站维护，处于神游状态！
